{
 "title": "sequencer loadtest",
 "time": { "from": "2023-09-12T14:40:19.459Z", "to": "2023-09-12T15:20:58.575Z" },
 "templating": {
  "list": [
   { "name": "test_id", "query": { "query": "label_values(test_id)" } }
  ]
 },
 "panels": [
  {
   "title": "RAM utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{test_id=\"$test_id\"} - node_memory_MemFree_bytes{test_id=\"$test_id\"} - (node_memory_Cached_bytes{test_id=\"$test_id\"} + node_memory_Buffers_bytes{test_id=\"$test_id\"} + node_memory_SReclaimable_bytes{test_id=\"$test_id\"}))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{test_id=\"$test_id\"} - node_memory_MemFree_bytes{test_id=\"$test_id\"} - (node_memory_Cached_bytes{test_id=\"$test_id\"} + node_memory_Buffers_bytes{test_id=\"$test_id\"} + node_memory_SReclaimable_bytes{test_id=\"$test_id\"}))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(node_memory_MemTotal_bytes{test_id=\"$test_id\"} - node_memory_MemFree_bytes{test_id=\"$test_id\"} - (node_memory_Cached_bytes{test_id=\"$test_id\"} + node_memory_Buffers_bytes{test_id=\"$test_id\"} + node_memory_SReclaimable_bytes{test_id=\"$test_id\"}))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(rate(sum(node_cpu_seconds_total{job=\"zksync-bft-loadtest-node-exporter\",test_id=\"$test_id\",mode!=\"idle\"}) by (instance)[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min(rate(sum(node_cpu_seconds_total{job=\"zksync-bft-loadtest-node-exporter\",test_id=\"$test_id\",mode!=\"idle\"}) by (instance)[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "avg(rate(sum(node_cpu_seconds_total{job=\"zksync-bft-loadtest-node-exporter\",test_id=\"$test_id\",mode!=\"idle\"}) by (instance)[1m]))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "bytes sent / replica / s (total and by RPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(network_rpc_message_size_bytes_sum{test_id=\"$test_id\",type=~\"req_sent|resp_sent\"}[1m])) by (type,method,submethod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.1, rate(network_tcp_sent_bytes{test_id=\"$test_id\"}[1m]))",
     "legendFormat": "total, 10th percentile"
    },
    {
     "expr": "quantile(0.5, rate(network_tcp_sent_bytes{test_id=\"$test_id\"}[1m]))",
     "legendFormat": "total, 50th percentile"
    },
    {
     "expr": "quantile(0.9, rate(network_tcp_sent_bytes{test_id=\"$test_id\"}[1m]))",
     "legendFormat": "total, 90th percentile"
    },
    {
     "expr": "quantile(1., rate(network_tcp_sent_bytes{test_id=\"$test_id\"}[1m]))",
     "legendFormat": "total, max"
    }
   ]
  },
  {
   "title": "messages sent / s / replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(avg(network_rpc_latency_seconds_count{test_id=\"$test_id\",type=\"client_send_recv\"}) by (method,submethod) [1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus RPC latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"consensus\",type=\"client_send_recv\",submethod=\"LeaderPrepare\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ping roundtrip",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finalized blocks/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(max(executor_finalized_block_number{test_id=\"$test_id\"})[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized block number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(executor_finalized_block_number{test_id=\"$test_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(executor_finalized_block_number{test_id=\"$test_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "replica view timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(consensus_replica_view_timeout_seconds{test_id=\"$test_id\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(consensus_replica_view_timeout_seconds{test_id=\"$test_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Commit phase latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(consensus_leader_commit_phase_latency_seconds_bucket{test_id=\"$test_id\"}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg consensus message processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sum (consensus_leader_processing_latency_seconds_sum{test_id=\"$test_id\"}) by (type)[1m])/rate(sum (consensus_leader_processing_latency_seconds_count{test_id=\"$test_id\"}) by (type)[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sum (consensus_replica_processing_latency_seconds_sum{test_id=\"$test_id\"}) by (type)[1m])/rate(sum (consensus_replica_processing_latency_seconds_count{test_id=\"$test_id\"}) by (type)[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "instance location",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "count(network_consensus_inbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(label_replace(network_consensus_inbound_connections{test_id=\"$test_id\"},\"region\",\"$1\",\"zone\",\"(.*)-.*-.*\")) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "min(network_gossip_inbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "min_gossip_inbound"
    },
    {
     "expr": "min(network_gossip_outbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "min_gossip_outbound"
    },
    {
     "expr": "min(network_consensus_inbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "min_consensus_inbound"
    },
    {
     "expr": "min(network_consensus_outbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "min_consensus_outbound"
    },
    {
     "expr": "avg(network_gossip_inbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "avg_gossip_inbound"
    },
    {
     "expr": "avg(network_gossip_outbound_connections{test_id=\"$test_id\"})",
     "legendFormat": "avg_gossip_outbound"
    }
   ]
  },
  {
   "title": "new connections globally/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(network_tcp_established{test_id=\"$test_id\",direction=\"inbound\"}[1m]))",
     "legendFormat": "new inbound"
    }
   ]
  },
  {
   "title": "% of theoretical max block rate",
   "type": "timeseries",
   "description": "Fastest hotstuff requires 2 roundtrips per view and 4/5 of signatures. This figure shows how many blocks/s we get compared to ideal situation in which message processing was infinitely fast. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg((min(histogram_quantile(0.8,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m]))) by (instance))/(min(rate(consensus_leader_commit_phase_latency_seconds_sum{test_id=\"$test_id\"}[1m])/rate(consensus_leader_commit_phase_latency_seconds_count{test_id=\"$test_id\"}[1m])) by (instance)))",
     "legendFormat": "actual commit phase rate"
    },
    {
     "expr": "2*avg(histogram_quantile(0.8,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m])))*rate(max(executor_finalized_block_number{test_id=\"$test_id\"})[1m])",
     "legendFormat": "actual block rate"
    },
    {
     "expr": "avg(2*histogram_quantile(0.8,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m]))/(3*histogram_quantile(0.66,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m]))))",
     "legendFormat": "theoretical optimum for 2/3 signatures 3 roundtrips"
    },
    {
     "expr": "1",
     "legendFormat": "theoretical optimum for 4/5 signatures 2 roundtrips"
    },
    {
     "expr": "1/(\n    1/(avg(histogram_quantile(0.8,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m])))*rate(max(executor_finalized_block_number{test_id=\"$test_id\"})[1m]))\n-\n    1/avg((min(histogram_quantile(0.8,rate(network_rpc_latency_seconds_bucket{test_id=\"$test_id\",method=\"ping\",type=\"client_send_recv\"}[1m]))) by (instance))/(min(rate(consensus_leader_commit_phase_latency_seconds_sum{test_id=\"$test_id\"}[1m])/rate(consensus_leader_commit_phase_latency_seconds_count{test_id=\"$test_id\"}[1m])) by (instance)))\n)",
     "legendFormat": "actual prepare phase rate (approx)"
    }
   ]
  },
  {
   "title": "Avg RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(avg(rate(network_rpc_latency_seconds_sum{test_id=\"$test_id\",type=~\"client_send_recv\"}[30s])/rate(network_rpc_latency_seconds_count{test_id=\"$test_id\",type=~\"client_send_recv\",method!=\"sync_validator_addrs\"}[30s])) by (method,submethod,type))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}