name: coverage

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  RUSTFLAGS: "-Dwarnings -C linker=clang -C link-arg=-fuse-ld=lld"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  RUST_BACKTRACE: "1"

jobs:
  check:
    name: Rust project
    runs-on: [self-hosted, ci-runner]

    defaults:
      run:
        working-directory: ./node

    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.8.3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: run tarpaulin
        run: cargo tarpaulin --out xml --engine llvm -- --test-threads 1
        env:
          RUST_LOG: 'network=trace,sync_blocks=trace,consensus=trace'

      #- name: Upload to codecov.io
      #  uses: codecov/codecov-action@v1.0.2
      #  with:
      #    token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
