name: coverage

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"
  RUSTFLAGS: "-Dwarnings -C linker=clang -C link-arg=-fuse-ld=lld"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  RUST_BACKTRACE: "1"

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./node

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - name: install tarpaulin
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-tarpaulin
      - name: run tarpaulin
        run: cargo tarpaulin --out xml --manifest-path node/Cargo.toml -- --test-threads 1
        env:
          RUST_LOG: 'network=trace,sync_blocks=trace,consensus=trace'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
