name: Specification testing

on:
  pull_request:
    paths:
      - "spec/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Install quint
        run: npm i @informalsystems/quint@0.20.0 -g

      - name: Run test
        run: cd spec && make test
